### PR TITLE
Fix scope link

### PR DESCRIPTION
**Pull request by astrojuanlu**
Closes gh-150

(Didn't test this locally 🤞🏽)

### CODE REVIEW

**Comment by astrojuanlu** [comment]
Now it seems to work: https://output.circle-artifacts.com/output/job/44005f92-37a6-4757-96a5-31c74d82b5cb/artifacts/0/html/how-to/author-guide.html#is-your-package-in-scope-for-pyopensci

**Comment by NickleDave** [comment]
🙌 you beat me to the PR! Thank you @astrojuanlu!

**Comment by lwasser** [comment]
thank you so much for this @astrojuanlu

**Comment by lwasser** [comment]
@all-contributors please add @astrojuanlu for code, review

**Pull request merged**
