### PR TITLE
Use long form command-line argument for "self-documentation"

### PR DESCRIPTION
**Pull request by nutjob4life**
I recommend always using long-form command-line arguments (where available) in documentation. It helps make documentation more "documentary"

### CODE REVIEW

**Comment by lwasser** [comment]
hey there @nutjob4life that is a good idea. maybe we can add a breakout box about using `pip install -e .` vs long form as well ?

may i ask - how did you find us here?

**Comment by lwasser** [comment]
@all-contributors please add @nutjob4life for code, review

**Comment by lwasser** [comment]
the CI break is a small link issue that i fixed in another PR recently. so this can be merged once we decide we want to go this route (which i think makes sense i just want to get the communities input first!)

**Comment by nutjob4life** [comment]
> hey there @nutjob4life that is a good idea. maybe we can add a breakout box about using `pip install -e .` vs long form as well ?
> 
> may i ask - how did you find us here?

That's a good question! I'm not sure how I ended up here.

**Comment by lwasser** [comment]
Merging this! thanks again @nutjob4life !!

**Pull request merged**
